language: android

android:
  components:
    - platform-tool
    - tool
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

jdk:
  - oraclejdk8

sudo: false

before_script:
 - chmod +x gradlew

script:
  - ./gradlew clean build
